### ISSUE TITLE
Write 5 new Dedicated Test in 'C'

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/rvc_asap#41]
1. Int multiplication test. (positive, negative, etc.)
2. Test Integer Divider & modulo 
3. Test Simple floating point arithmetic. (Add, Sub, positive, negative,)
4. Test Advances floating-point arithmetic. (Mul, Div)
5. Test "Char" array - Byte Accessible.

**Comment by amichai-bd** [comment]
You added snapshots checker for the new tests?

**Comment by gilyaakov** [comment]
Yes we added.
