### ISSUE TITLE
Summary of running 1st program on rvc_asap

### ISSUE THREAD

**Issue by matanesh** [amichai-bd/rvc_asap#8]
- after compiling all what reqiuerd we use the vsim.exe to execute the TB we write on our rvc_asap through the "backdor" 
 - open the Wave/Signal view and check our program and the various command that used.
 
 - signals we check:
 - Pc, 
 - ctrlAluOp,
 
 command we work on:
 - lui, 
 - jal,
 -  sw,
 -  lw,
 -  add

**Comment by amichai-bd** [comment]
Sounds good

**Comment by amichai-bd** [comment]
I added a new option for "discussions" in this git repository - Please use it for this kind of update.
@gilyaakov @matanesh
