### ISSUE TITLE
add to the build print list off Pass, Fail, and Unknow results

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/rvc_asap#95]
add to the build print list off Pass, Fail, and Unknow results
@danielk532

**Comment by danielk532** [comment]
Done.
![image](https://user-images.githubusercontent.com/83028235/204164735-b9264d8d-4acb-44c1-b2c0-c87da702e941.png)

**Comment by amichai-bd** [comment]
This looks great!
Please send a pull request - Once its merged to main we can close this issue
